version: 2

jobs:
  build:
    docker:
        - image: docker:17.05.0-ce-git
    working_directory: ~/repo

    steps:
      - checkout
      - run: 
          name: Build and publish docker image
          command: |
            TAG="${CIRCLE_SHA1}"
            docker build -t sptkl/edm-qaqc-app:$TAG .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push sptkl/edm-qaqc-app:$TAG
            docker tag sptkl/edm-qaqc-app:$TAG sptkl/edm-qaqc-app:latest
            docker push sptkl/edm-qaqc-app:latest